# Generated by Django 6.1 on 2026-08-23 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='combos/')),
                ('precio_promocional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'combo',
                'verbose_name_plural': 'combos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'producto del combo',
                'verbose_name_plural': 'productos del combo',
            },
        ),
        migrations.AlterModelOptions(
            name='varianteproducto',
            options={'ordering': ['orden', 'modalidad', 'nombre'], 'verbose_name': 'variante de producto', 'verbose_name_plural': 'variantes de producto'},
        ),
        migrations.RemoveConstraint(
            model_name='varianteproducto',
            name='variante_unica_por_producto',
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('cocinada', 'Cocinadas'), ('congelada', 'Congeladas')], help_text='Solo se usa en productos con dos formas de compra (ej. Empanadas: cocinadas/congeladas).', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='varianteproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'nombre', 'modalidad'), name='variante_unica_por_producto'),
        ),
        migrations.AddField(
            model_name='comboitem',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogo.combo'),
        ),
        migrations.AddField(
            model_name='comboitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='catalogo.producto'),
        ),
        migrations.AddConstraint(
            model_name='comboitem',
            constraint=models.UniqueConstraint(fields=('combo', 'producto'), name='producto_unico_por_combo'),
        ),
    ]
