# Generated by Django 6.1 on 2026-08-25 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_reestructurar_variantes_por_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen_tamano',
            field=models.PositiveIntegerField(default=260, help_text='Alto de la imagen en px (el ancho se ajusta proporcionalmente).', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)], verbose_name='tamaño'),
        ),
    ]
