# Generated by Django 6.1 on 2026-08-27 03:25

import django.core.validators
from django.db import migrations, models


def convertir_posicion_a_porcentaje(apps, schema_editor):
    """Convierte imagen_pos_x/y de Categoria del rango viejo (-1000..1000,
    0 = sin ajuste) al nuevo rango en % (0..100, 50 = centro), preservando el
    mismo resultado visual: la fórmula CSS que consume estos valores se
    actualiza en paralelo con el mismo factor de conversión."""
    Categoria = apps.get_model("catalogo", "Categoria")
    for categoria in Categoria.objects.all():
        nuevo_x = round(50 + (categoria.imagen_pos_x or 0) / 1000 * 50)
        nuevo_y = round(50 + (categoria.imagen_pos_y or 0) / 1000 * 50)
        categoria.imagen_pos_x = max(0, min(100, nuevo_x))
        categoria.imagen_pos_y = max(0, min(100, nuevo_y))
        categoria.save(update_fields=["imagen_pos_x", "imagen_pos_y"])


def revertir_posicion_a_porcentaje(apps, schema_editor):
    Categoria = apps.get_model("catalogo", "Categoria")
    for categoria in Categoria.objects.all():
        viejo_x = round((categoria.imagen_pos_x - 50) / 50 * 1000)
        viejo_y = round((categoria.imagen_pos_y - 50) / 50 * 1000)
        categoria.imagen_pos_x = max(-1000, min(1000, viejo_x))
        categoria.imagen_pos_y = max(-1000, min(1000, viejo_y))
        categoria.save(update_fields=["imagen_pos_x", "imagen_pos_y"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_categoria_imagen_tamano'),
    ]

    operations = [
        migrations.RunPython(convertir_posicion_a_porcentaje, revertir_posicion_a_porcentaje),
        migrations.AddField(
            model_name='combo',
            name='imagen_pos_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='Posición horizontal en % (0 = izquierda, 50 = centro, 100 = derecha).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='posición horizontal (X)'),
        ),
        migrations.AddField(
            model_name='combo',
            name='imagen_pos_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='Posición vertical en % (0 = arriba, 50 = centro, 100 = abajo).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='posición vertical (Y)'),
        ),
        migrations.AddField(
            model_name='combo',
            name='imagen_zoom',
            field=models.PositiveSmallIntegerField(default=100, help_text='Escala de la imagen dentro de su recuadro, en % (100 = ajuste normal).', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(200)], verbose_name='zoom'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_pos_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='Posición horizontal en % (0 = izquierda, 50 = centro, 100 = derecha).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='posición horizontal (X)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_pos_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='Posición vertical en % (0 = arriba, 50 = centro, 100 = abajo).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='posición vertical (Y)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_zoom',
            field=models.PositiveSmallIntegerField(default=100, help_text='Escala de la imagen dentro de su recuadro, en % (100 = ajuste normal).', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(200)], verbose_name='zoom'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen_pos_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='Posición horizontal en % (0 = izquierda, 50 = centro, 100 = derecha).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='posición horizontal (X)'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen_pos_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='Posición vertical en % (0 = arriba, 50 = centro, 100 = abajo).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='posición vertical (Y)'),
        ),
    ]
