# Generated by Django 6.1 on 2026-08-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_posicionamiento_porcentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='mostrar_en_inicio',
            field=models.BooleanField(default=True, help_text='Si está desactivado, la categoría no aparece en la sección de categorías del Inicio.', verbose_name='mostrar en inicio'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='mostrar_en_productos',
            field=models.BooleanField(default=True, help_text='Si está desactivado, la categoría no aparece en la sección Productos ni en sus filtros.', verbose_name='mostrar en productos'),
        ),
    ]
