# Generated by Django 6.1 on 2026-08-29 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_categoria_mostrar_en_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen_mobile_pos_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='Posición horizontal en % dentro de la tarjeta mobile (0 = izquierda, 50 = centro, 100 = derecha).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='posición horizontal mobile (X)'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen_mobile_pos_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='Posición vertical en % dentro de la tarjeta mobile (0 = arriba, 50 = centro, 100 = abajo).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='posición vertical mobile (Y)'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen_mobile_tamano',
            field=models.PositiveSmallIntegerField(default=100, help_text='Escala de la imagen dentro de su recuadro mobile, en % (100 = ajuste normal, sin recortar).', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)], verbose_name='tamaño mobile'),
        ),
    ]
