# Generated by Django 6.1 on 2026-08-29 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_categoria_imagen_mobile_pos_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen_mobile_pos_x',
            field=models.SmallIntegerField(default=50, help_text='Posición horizontal en % relativo a toda la tarjeta mobile (50 = centro; puede salir de 0-100 para mover la imagen bien hacia los costados).', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(200)], verbose_name='posición horizontal mobile (X)'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen_mobile_pos_y',
            field=models.SmallIntegerField(default=50, help_text='Posición vertical en % relativo a toda la tarjeta mobile (50 = centro; puede salir de 0-100 para mover la imagen bien hacia arriba/abajo).', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(200)], verbose_name='posición vertical mobile (Y)'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen_mobile_tamano',
            field=models.PositiveSmallIntegerField(default=100, help_text='Escala de la imagen dentro de la tarjeta mobile, en % (100 = tamaño base, sin recortar).', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(400)], verbose_name='tamaño mobile'),
        ),
    ]
