# Generated by Django 6.1 on 2026-09-01 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_alter_categoria_imagen_mobile_pos_x_and_more'),
        ('pedidos', '0002_alter_itempedido_producto_alter_itempedido_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_pedido', to='catalogo.combo'),
        ),
    ]
