# Generated by Django 6.1 on 2026-08-22 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='Capricho', max_length=150)),
                ('eslogan', models.CharField(blank=True, default='Boutique Empanadas & Bakery', max_length=255)),
                ('whatsapp_numero', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Ingresá el número en formato internacional, solo dígitos y opcionalmente un '+' inicial.", regex='^\\+?\\d{8,15}$')])),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('instagram', models.URLField(blank=True)),
                ('dias_anticipacion_pedido', models.PositiveIntegerField(default=1, help_text='Días mínimos de anticipación exigidos para un pedido. Única fuente de verdad de esta regla.')),
                ('envio_habilitado', models.BooleanField(default=True)),
                ('costo_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('envio_gratis_desde', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración del negocio',
                'verbose_name_plural': 'configuración del negocio',
            },
        ),
    ]
