# Generated by Django 6.1 on 2026-08-23 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='pedidos_imagen',
            field=models.ImageField(blank=True, help_text="Imagen de la tarjeta 'Pedidos' en la página de inicio.", null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='pedidos_imagen_pos_x',
            field=models.IntegerField(default=0, help_text='Ajuste horizontal en px sobre la posición actual de la imagen. Negativo = izquierda, positivo = derecha.', validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='pedidos_imagen_pos_y',
            field=models.IntegerField(default=0, help_text='Ajuste vertical en px sobre la posición actual de la imagen. Negativo = arriba, positivo = abajo.', validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='pedidos_imagen_tamano',
            field=models.PositiveIntegerField(default=260, help_text='Alto de la imagen en px en la tarjeta de inicio (el ancho se ajusta proporcionalmente).', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(600)]),
        ),
    ]
