# Generated by Django 6.1 on 2026-08-23 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_configuracionnegocio_pedidos_imagen_datos_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='pedidos_imagen',
            field=models.ImageField(blank=True, help_text="Imagen de la tarjeta 'Pedidos' en la página de inicio.", null=True, upload_to='categorias/', verbose_name='imagen de pedidos en portada'),
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='pedidos_imagen_pos_x',
            field=models.IntegerField(default=0, help_text='Ajuste horizontal en px sobre la posición actual. Negativo = izquierda, positivo = derecha.', validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)], verbose_name='posición horizontal (X)'),
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='pedidos_imagen_pos_y',
            field=models.IntegerField(default=0, help_text='Ajuste vertical en px sobre la posición actual. Negativo = arriba, positivo = abajo.', validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)], verbose_name='posición vertical (Y)'),
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='pedidos_imagen_tamano',
            field=models.PositiveIntegerField(default=260, help_text='Alto de la imagen en px (el ancho se ajusta proporcionalmente).', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(600)], verbose_name='tamaño'),
        ),
    ]
