# Generated by Django 6.1 on 2026-08-25 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_configuracionnegocio_pedidos_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='pedidos_imagen_tamano',
            field=models.PositiveIntegerField(default=260, help_text='Alto de la imagen en px (el ancho se ajusta proporcionalmente).', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)], verbose_name='tamaño'),
        ),
    ]
