# Generated by Django 6.1 on 2026-08-27 03:25

import django.core.validators
from django.db import migrations, models


def convertir_posicion_a_porcentaje(apps, schema_editor):
    """Convierte pedidos_imagen_pos_x/y del rango viejo (-1000..1000, 0 = sin
    ajuste) al nuevo rango en % (0..100, 50 = centro), preservando el mismo
    resultado visual (ver catalogo.migrations.0010 para la misma conversión
    aplicada a Categoria, y la fórmula CSS actualizada en paralelo)."""
    ConfiguracionNegocio = apps.get_model("panel", "ConfiguracionNegocio")
    for config in ConfiguracionNegocio.objects.all():
        nuevo_x = round(50 + (config.pedidos_imagen_pos_x or 0) / 1000 * 50)
        nuevo_y = round(50 + (config.pedidos_imagen_pos_y or 0) / 1000 * 50)
        config.pedidos_imagen_pos_x = max(0, min(100, nuevo_x))
        config.pedidos_imagen_pos_y = max(0, min(100, nuevo_y))
        config.save(update_fields=["pedidos_imagen_pos_x", "pedidos_imagen_pos_y"])


def revertir_posicion_a_porcentaje(apps, schema_editor):
    ConfiguracionNegocio = apps.get_model("panel", "ConfiguracionNegocio")
    for config in ConfiguracionNegocio.objects.all():
        viejo_x = round((config.pedidos_imagen_pos_x - 50) / 50 * 1000)
        viejo_y = round((config.pedidos_imagen_pos_y - 50) / 50 * 1000)
        config.pedidos_imagen_pos_x = max(-1000, min(1000, viejo_x))
        config.pedidos_imagen_pos_y = max(-1000, min(1000, viejo_y))
        config.save(update_fields=["pedidos_imagen_pos_x", "pedidos_imagen_pos_y"])


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_configuracionnegocio_pedidos_imagen_tamano'),
    ]

    operations = [
        migrations.RunPython(convertir_posicion_a_porcentaje, revertir_posicion_a_porcentaje),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='portada_imagen',
            field=models.ImageField(blank=True, help_text='Foto principal del hero en la página de inicio. Si no se sube ninguna, se usa la imagen por defecto del sitio.', null=True, upload_to='productos/', verbose_name='imagen principal de la portada'),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='portada_imagen_pos_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='Posición horizontal en % (0 = izquierda, 50 = centro, 100 = derecha).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='posición horizontal (X)'),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='portada_imagen_pos_y',
            field=models.PositiveSmallIntegerField(default=32, help_text='Posición vertical en % (0 = arriba, 50 = centro, 100 = abajo).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='posición vertical (Y)'),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='portada_imagen_zoom',
            field=models.PositiveSmallIntegerField(default=100, help_text='Escala de la imagen dentro de su recuadro, en % (100 = ajuste normal).', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(200)], verbose_name='zoom'),
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='pedidos_imagen_pos_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='Posición horizontal en % (0 = izquierda, 50 = centro, 100 = derecha).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='posición horizontal (X)'),
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='pedidos_imagen_pos_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='Posición vertical en % (0 = arriba, 50 = centro, 100 = abajo).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='posición vertical (Y)'),
        ),
    ]
